# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py312"

[lint]
select = [
    "ALL",
]

ignore = [
    "ANN001", # Missing type annotation for function argument
    "ANN101", # Missing type annotation for `self` in method
    "ANN201", # Missing return type annotation for public function
    "ANN202", # Missing return type annotation for private function
    "ANN204", # Missing return type annotation for special method
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "ARG001", # Unused function argument: `hass`
    "BLE001", # Do not catch blind exception: `Exception
    "COM812", # incompatible with formatter
    "D102", # Missing docstring in public method
    "D107", # Missing docstring in `__init__`
    "D203", # no-blank-line-before-class (incompatible with formatter)
    "D212", # multi-line-summary-first-line (incompatible with formatter)
    "D400", # First line should end with a period
    "D401", # First line of docstring should be in imperative mood
    "D404", # First word of the docstring should not be "This"
    "D415", # First line should end with a period, question mark, or exclamation point
    "FBT003", # Boolean positional value in function call
    "ISC001", # incompatible with formatter
    "PLR0913", # Too many arguments in function definition
    "PTH110", # `os.path.exists()` should be replaced by `Path.exists()`
    "RET505", # Unnecessary `else` after `return` statement
    "TRY300", # Consider moving this statement to an `else` block
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25
